[workspace]
members = ["crates/core", "crates/services", "crates/desktop"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "2"
turbodbn-core = { path = "crates/core" }
turbodbn-services = { path = "crates/services" }
gpui = "=0.2.2"
gpui-component = "=0.5.1"
gpui-component-assets = "=0.5.1"

[profile.release]
lto = "thin"
codegen-units = 1

[profile.dev]
debug = 1
